cache:
  directories:
  - "$HOME/google-cloud-sdk"
language: go
services:
- docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
# security account.json
- openssl aes-256-cbc -K $encrypted_df2253688184_key -iv $encrypted_df2253688184_iv -in account.json.enc -out account.json -d
# installing golang dependencies
- go get ./...
# running unit and integration tests
- make app action=test
# add coverage report
- go get github.com/mattn/goveralls
# build docker image
- make docker action=build
# install google sdk
- if [ ! -d $HOME/google-cloud-sdk/bin ]; then rm -rf $HOME/google-cloud-sdk; curl
  https://sdk.cloud.google.com | bash > /dev/null; fi
- source $HOME/google-cloud-sdk/path.bash.inc
# login into gcr service with docker
- docker login -u _json_key --password-stdin https://gcr.io < account.json
# push docker image on gcr service
- docker push ${CONTAINER_TAG}:${TRAVIS_COMMIT}
script:
- "$GOPATH/bin/goveralls -service=go-cicd"
- gcloud config set project ${PROJECT_ID}
deploy:
- provider: script
  script: gcloud run deploy go-cicd-master --image ${CONTAINER_TAG}:${TRAVIS_COMMIT}
    --region us-east1 --platform managed --allow-unauthenticated
  on:
    branch: master
- provider: script
  script: gcloud run deploy ${TRAVIS_REPO_SLUG/\//-}-${TRAVIS_BUILD_ID} --image ${CONTAINER_TAG}:${TRAVIS_COMMIT}
    --region us-east1 --platform managed --allow-unauthenticated
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != "master"