apiVersion: v1
kind: Service
metadata:
  name: servicea
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: "80-to-8080"
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: "443-to-8080"
      protocol: TCP
      port: 443
      targetPort: 8080
  selector:
    app: servicea
  type: NodePort